/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import allgemein.Bilder;
import allgemein.DateiManager;
import allgemein.MyTimer;
import allgemein.NotificationNames;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.Icon;
import javax.swing.JLabel;
import notificationcenter.*;
import model.*;
import java.util.TimerTask;
import allgemein.DateiManager;
/**
 *
 * @author macbookpro15
 */
public class KuhstallGUI extends javax.swing.JFrame {

    DateiManager dateiManager = new DateiManager(this); 

        
    public static final int ANIMATION_DURATION /*secends*/ = 3;
    public KuhstallGUI() {
        initComponents();

    }

    public void doStuff() {
        //do stuff here
    }

    public void updateWithCowData(Kuh cow, int currentCowIndex, int totalCowsInStock) {
        int index = currentCowIndex + 1;
        cowDataTextArea.setText(cow.toString());
        currentCowIndexLabel.setText("" + index + "/" + totalCowsInStock);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        futterMengeTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        addFutterMengeButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        StoredFoodAmountLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        demandFoodLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        feedCowsButton = new javax.swing.JButton();
        melkenButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        milkTankVolumeLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        deliverMilkButtonPressed = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        cowImageLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        cowDataTextArea = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        showFirstCowData = new javax.swing.JToggleButton();
        showPreviousCowData = new javax.swing.JToggleButton();
        currentCowIndexLabel = new javax.swing.JLabel();
        showNextCowData = new javax.swing.JButton();
        showLastCowData = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        buyCowMenuItem = new javax.swing.JMenuItem();
        bearNewCowMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        copyrightMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Kuhstall");

        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Kuhstall verwalten"));

        futterMengeTextField.setText("0.5");
        futterMengeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                futterMengeTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Futter in t");

        addFutterMengeButton.setText("einlagern");
        addFutterMengeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFutterMengeButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Scheuneninhalt:");

        StoredFoodAmountLabel.setText("0.0");

        jLabel5.setText("kg");

        demandFoodLabel.setText("0.0");

        jLabel7.setText("kg");

        feedCowsButton.setText("alle tiere füttern");
        feedCowsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feedCowsButtonActionPerformed(evt);
            }
        });

        melkenButton.setText("alle Kühe melken");
        melkenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                melkenButtonActionPerformed(evt);
            }
        });

        jLabel8.setText("Milchtankinhalt:");

        milkTankVolumeLabel.setText("0.0");

        jLabel10.setText("Liter");

        deliverMilkButtonPressed.setText("Milch abliefern");
        deliverMilkButtonPressed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverMilkButtonPressedActionPerformed(evt);
            }
        });

        jLabel11.setText("Futterbedarf");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(feedCowsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(melkenButton))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(futterMengeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(addFutterMengeButton))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(StoredFoodAmountLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5))
                    .addComponent(deliverMilkButtonPressed, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(41, 41, 41)
                        .addComponent(demandFoodLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(milkTankVolumeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(futterMengeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(addFutterMengeButton))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(StoredFoodAmountLabel)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(demandFoodLabel)
                    .addComponent(jLabel7)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(feedCowsButton)
                    .addComponent(melkenButton))
                .addGap(56, 56, 56)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(milkTankVolumeLabel)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deliverMilkButtonPressed)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cowImageLabel.setBackground(new java.awt.Color(153, 153, 153));
        cowImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/z_bilder/kuh - steht.gif"))); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Kuhdaten"));

        cowDataTextArea.setColumns(20);
        cowDataTextArea.setRows(5);
        jScrollPane1.setViewportView(cowDataTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Datensatzsteuerung"));

        showFirstCowData.setText("|<");
        showFirstCowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showFirstCowDataActionPerformed(evt);
            }
        });

        showPreviousCowData.setText("<");
        showPreviousCowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPreviousCowDataActionPerformed(evt);
            }
        });

        currentCowIndexLabel.setText("0");

        showNextCowData.setText(">");
        showNextCowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showNextCowDataActionPerformed(evt);
            }
        });

        showLastCowData.setText(">|");
        showLastCowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showLastCowDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showFirstCowData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showPreviousCowData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currentCowIndexLabel)
                .addGap(33, 33, 33)
                .addComponent(showNextCowData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showLastCowData)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(showFirstCowData)
                    .addComponent(showPreviousCowData)
                    .addComponent(currentCowIndexLabel)
                    .addComponent(showNextCowData)
                    .addComponent(showLastCowData))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jMenu1.setText("Datei");

        jMenuItem4.setText("öffnen");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("speichern");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("speichern unter");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Bearbeiten");

        buyCowMenuItem.setText("Kuh kaufen");
        buyCowMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyCowMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(buyCowMenuItem);

        bearNewCowMenuItem.setText("Kalb wird geboren");
        bearNewCowMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bearNewCowMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(bearNewCowMenuItem);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Extras");

        copyrightMenuItem.setText("@coin side of life");
        copyrightMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyrightMenuItemActionPerformed(evt);
            }
        });
        jMenu3.add(copyrightMenuItem);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(256, 256, 256)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cowImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cowImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void futterMengeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_futterMengeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_futterMengeTextFieldActionPerformed

    private void addFutterMengeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFutterMengeButtonActionPerformed
        // Food in tonnen
        double newFoodAmount = Double.parseDouble(futterMengeTextField.getText());
        double foodInKg = newFoodAmount * 1000.0;
        NotificationCenter.shared.processNotification(NotificationNames.ADD_FOOD_TO_STORE, foodInKg);


    }//GEN-LAST:event_addFutterMengeButtonActionPerformed

    private void showFirstCowDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showFirstCowDataActionPerformed
        NotificationCenter.shared.processNotification(NotificationNames.SHOW_FIRST_COW_DATA);
    }//GEN-LAST:event_showFirstCowDataActionPerformed

    private void showPreviousCowDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPreviousCowDataActionPerformed
        NotificationCenter.shared.processNotification(NotificationNames.SHOW_PREVIOUS_COW_DATA);

    }//GEN-LAST:event_showPreviousCowDataActionPerformed

    private void showLastCowDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showLastCowDataActionPerformed
        NotificationCenter.shared.processNotification(NotificationNames.SHOW_LAST_COW_DATA);

    }//GEN-LAST:event_showLastCowDataActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        dateiManager.saveFile();
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void buyCowMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyCowMenuItemActionPerformed
        NotificationCenter.shared.processNotification(NotificationNames.SEND_BUY_COW_GUI_TO_FRONT);

    }//GEN-LAST:event_buyCowMenuItemActionPerformed

    private void showNextCowDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showNextCowDataActionPerformed
        NotificationCenter.shared.processNotification(NotificationNames.SHOW_NEXT_COW_DATA);

    }//GEN-LAST:event_showNextCowDataActionPerformed

    private void feedCowsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feedCowsButtonActionPerformed
        NotificationCenter.shared.processNotification(NotificationNames.FEED_COWS);

    }//GEN-LAST:event_feedCowsButtonActionPerformed

    private void melkenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_melkenButtonActionPerformed
        NotificationCenter.shared.processNotification(NotificationNames.MELK_ALL_COWS);
    }//GEN-LAST:event_melkenButtonActionPerformed

    private void deliverMilkButtonPressedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverMilkButtonPressedActionPerformed
        NotificationCenter.shared.processNotification(NotificationNames.DELIVER_MILK);
    }//GEN-LAST:event_deliverMilkButtonPressedActionPerformed

    private void copyrightMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyrightMenuItemActionPerformed
        NotificationCenter.shared.processNotification(NotificationNames.SEND_COPYRIGHT_GUI_TO_FRONT);

    }//GEN-LAST:event_copyrightMenuItemActionPerformed

    private void bearNewCowMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bearNewCowMenuItemActionPerformed
        NotificationCenter.shared.processNotification(NotificationNames.SEND_BORE_NEW_CALF_GUI_TO_FRONT);
    }//GEN-LAST:event_bearNewCowMenuItemActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        dateiManager.selectFile();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        dateiManager.saveFile();
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KuhstallGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KuhstallGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KuhstallGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KuhstallGUI.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new KuhStallGUI().setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new KuhStallGUI().setVisible(true);
//            }
//        });
    }

    // LABEL GETTERs
    public JLabel getStoredFoodAmountLabel() {
        return StoredFoodAmountLabel;
    }

    public JLabel getDemandFoodLabel() {
        return demandFoodLabel;
    }

    public JLabel getMilkTankVolumeLabel() {
        return milkTankVolumeLabel;
    }

    public JLabel getCowImageLabel() {
        return cowImageLabel;
    }

    private Timer timer = new Timer();

    public void performAnimation(Icon icon) {
        this.performAnimation(icon, KuhstallGUI.ANIMATION_DURATION); 
    }
    
    public void performAnimation(Icon icon, int durationInSeconds) {
        cowImageLabel.setIcon(icon);
        timer.schedule(new TimerTask() {
            @Override
        public void run() {
               cowImageLabel.setIcon(Bilder.Kuh.STEHEND);
            }
        }, 1000 * durationInSeconds);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel StoredFoodAmountLabel;
    private javax.swing.JButton addFutterMengeButton;
    private javax.swing.JMenuItem bearNewCowMenuItem;
    private javax.swing.JMenuItem buyCowMenuItem;
    private javax.swing.JMenuItem copyrightMenuItem;
    private javax.swing.JTextArea cowDataTextArea;
    private javax.swing.JLabel cowImageLabel;
    private javax.swing.JLabel currentCowIndexLabel;
    private javax.swing.JButton deliverMilkButtonPressed;
    private javax.swing.JLabel demandFoodLabel;
    private javax.swing.JButton feedCowsButton;
    private javax.swing.JTextField futterMengeTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton melkenButton;
    private javax.swing.JLabel milkTankVolumeLabel;
    private javax.swing.JPanel panel;
    private javax.swing.JToggleButton showFirstCowData;
    private javax.swing.JButton showLastCowData;
    private javax.swing.JButton showNextCowData;
    private javax.swing.JToggleButton showPreviousCowData;
    // End of variables declaration//GEN-END:variables
}
